/*
 * Texture loading via stb_image.
 *
 * The images are loaded bottom-up (the game's texture coordinates assume the
 * OpenGL convention) and uploaded as RGB/RGBA.  Mipmaps are generated by the
 * driver with GL_GENERATE_MIPMAP instead of gluBuild2DMipmaps, so the port
 * does not need GLU at all.
 */
#include "Textures.h"
#include "Support.h"

#include <stdio.h>
#include <string.h>

#include "thirdparty/stb_image.h"

GLuint loadTexture(const char* filename_, GLenum minFilter, GLenum magFilter, bool mipmaps)
{
	char filename[1024];
	PlatformDataPath(filename_, filename, sizeof(filename));

	int width = 0, height = 0, channels = 0;
	stbi_set_flip_vertically_on_load(1);
	unsigned char *pixels = stbi_load(filename, &width, &height, &channels, 0);
	if (!pixels) {
		fprintf(stderr, "couldn't load file %s: %s\n", filename, stbi_failure_reason());
		return 0;
	}

	GLenum format;
	GLint  internalFormat;
	switch (channels) {
		case 1:  format = GL_LUMINANCE;       internalFormat = GL_LUMINANCE;       break;
		case 2:  format = GL_LUMINANCE_ALPHA; internalFormat = GL_LUMINANCE_ALPHA; break;
		case 3:  format = GL_RGB;             internalFormat = GL_RGB;             break;
		default: format = GL_RGBA;            internalFormat = GL_RGBA;            break;
	}

	GLuint tex = 0;
	glGenTextures(1, &tex);
	glBindTexture(GL_TEXTURE_2D, tex);
	glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, magFilter);
	glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, minFilter);

	glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
#ifdef __EMSCRIPTEN__
	/* WebGL has no GL_GENERATE_MIPMAP parameter - it builds the chain on
	   demand instead, which is what GL 3.0 settled on too. */
	glTexImage2D(GL_TEXTURE_2D, 0, internalFormat, width, height, 0,
	             format, GL_UNSIGNED_BYTE, pixels);
	if (mipmaps) glGenerateMipmap(GL_TEXTURE_2D);
#else
	if (mipmaps) {
		glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, GL_TRUE);
	}
	glTexImage2D(GL_TEXTURE_2D, 0, internalFormat, width, height, 0,
	             format, GL_UNSIGNED_BYTE, pixels);
	if (mipmaps) {
		glTexParameteri(GL_TEXTURE_2D, GL_GENERATE_MIPMAP, GL_FALSE);
	}
#endif

	stbi_image_free(pixels);
	return tex;
}
